/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.43).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.proofit.task.api;

import com.proofit.task.model.Bicycles;
import com.proofit.task.model.PremiumResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import jakarta.validation.Valid;

@jakarta.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2024-10-30T13:48:14.508+01:00")

@Validated
@Api(value = "calculate", description = "the calculate API")
@RequestMapping(value = "/api/v1")
public interface CalculateApi {

    @ApiOperation(value = "Calculate premiums for bicycle insurance policies", nickname = "calculatePost", notes = "Given a list of bicycle objects, this API will calculate the total premium associated with each bicycle.  ", response = PremiumResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully calculated premiums and risks for bicycle policies", response = PremiumResponse.class),
        @ApiResponse(code = 400, message = "Invalid input provided"),
        @ApiResponse(code = 500, message = "Server error occurred") })
    @RequestMapping(value = "/calculate",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<PremiumResponse> calculatePost(@ApiParam(value = "List of bicycle objects for which to calculate premiums" ,required=true )  @Valid @RequestBody Bicycles bicycles);

}
